// TYPES
const ADDED_TODO = 'ADDED_TODO';
const TOGGLED_TODO = 'TOGGLED_TODO';
const DELETED_TODO = 'DELETED_TODO';
const STARRED_TODO = 'STARRED_TODO';

export default { ADDED_TODO, TOGGLED_TODO, DELETED_TODO, STARRED_TODO };
